name: Check Baseimage and ioBroker versions

on:
  schedule:
    - cron: '42 23 * * *'
  workflow_dispatch:

jobs:
  check-and-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          repository: 'buanet/ioBroker.docker'
          token: ${{ secrets.ACTIONS_PAT }}

      - name: Get and write version
        id: version
        run: |
          LATESTRELEASE="$(curl -sL https://api.github.com/repos/buanet/ioBroker.docker/releases/latest | jq -r '.tag_name')"
          VERSION="$(cat .github/settings/.stable-version)"
          echo "myimage=iobroker/iobroker:$LATESTRELEASE" >> $GITHUB_ENV
          echo "baseimage=library/debian:bullseye-slim" >> $GITHUB_ENV

      - name: Docker Baseimage Checker
        id: baseimage
        uses: mkumatag/container-image-updater-action@v1.0.5
        with:
          base-image: '${{ env.baseimage }}'
          image: '${{ env.myimage }}'

      - name: Fetch ioBroker versions
        run: |
          curl -sL https://repo.iobroker.live/sources-dist.json | \
          jq -r '."js-controller".version' > .github/dependencies/.js-controller-version
          echo "[LOG] Fetched js-controller version is $(cat .github/dependencies/.js-controller-version)"
          curl -sL https://repo.iobroker.live/sources-dist.json | \
          jq -r '."admin".version' > .github/dependencies/.admin-version
          echo "[LOG] Fetched admin version is $(cat .github/dependencies/.admin-version)"
          curl -sL https://repo.iobroker.live/sources-dist.json | \
          jq -r '."backitup".version' > .github/dependencies/.backitup-version
          echo "[LOG] Fetched backitup version is $(cat .github/dependencies/.backitup-version)"
          curl -sL https://repo.iobroker.live/sources-dist.json | \
          jq -r '."discovery".version' > .github/dependencies/.discovery-version
          echo "[LOG] Fetched discovery version is $(cat .github/dependencies/.discovery-version)"

      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")

      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'buanet'
          git config --global user.email 'info@buanet.de'
          git commit -am "new ioBroker versions"
          git push

      - name: Trigger build debian latest (buanet)
        if: steps.baseimage.outputs.needs-update == 'true' || steps.git-check.outputs.modified == 'true'
        uses: benc-uk/workflow-dispatch@v1.2
        with:
          workflow: Build debian latest (buanet)
          repo: buanet/ioBroker.docker
          token: ${{ secrets.ACTIONS_PAT }}

      - name: Trigger build debian latest (iobroker)
        if: steps.baseimage.outputs.needs-update == 'true' || steps.git-check.outputs.modified == 'true'
        uses: benc-uk/workflow-dispatch@v1.2
        with:
          workflow: Build debian latest (iobroker)
          repo: buanet/ioBroker.docker
          token: ${{ secrets.ACTIONS_PAT }}
